### ISSUE TITLE
Cannot find module ./config

### ISSUE THREAD

**Issue by dustmoo** [moviepilot/seoserver#2]
Hi there,

I love the idea of using Memcached for the phantomjs SEO server. But I am having trouble installing your script.

I cloned the repository, updated the config.coffee file and installed dependancies using        

```
npm install
```

But when I run the server command I am getting the following:

```
module.js:340
throw err;
      ^
Error: Cannot find module './config'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/dustmoo/seoserver/lib/seoserver.js:18:19)
at Object.<anonymous> (/home/dustmoo/seoserver/lib/seoserver.js:311:4)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
```

Any Ideas?

**Comment by dustmoo** [comment]
Fixed.

I needed to compile the coffee script config. (You may want to mention that in your read me for coffescript newbs.

**Comment by laurentdebricon** [comment]
yes it's not written : 
npm install -g coffee-script
then coffee -c config.coffee 
then move config.js to the lib folder
